name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: |
          chmod 777 gradlew
          ./gradlew clean build
      - name: Docker Login
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Docker Build
        run: |
          docker build -t estohlmann/mcc-codeschool .
      - name: Push Image
        run: docker push estohlmann/mcc-codeschool:latest

  deploy:
    needs: build
    runs-on: [ec2-runner]
    steps:
      - name: Pull Docker Image
        run: |
          sudo docker pull estohlmann/mcc-codeschool:latest
      - name: Remove Container
        run: |
          sudo docker rm -f tic-tac-toe
      - name: Run Docker Container
        run: |
          sudo docker run -d -p 8080:8080 --name tic-tac-toe estohlmann/mcc-codeschool:latest